<?php
return [
  'Lottery'=>[
      'grade'=>[
          1=>[
              'value'=>0.0002,
              'lucky'=>100,
              'reward'=>5000000,
          ],
          2=>[
              'value'=>0.002,
              'lucky'=>100,
              'reward'=>100000,
          ],
          3=>[
              'value'=>0.01,
              'lucky'=>100,
              'reward'=>5000,
          ],
          4=>[
              'value'=>0.02,
              'lucky'=>100,
              'reward'=>1000,
          ],
          5=>[
              'value'=>0.2,
              'lucky'=>100,
              'reward'=>5,
          ],
      ],
      'cost'=>2,
      'number'=>10,
      ],
    'Learn'=>[
        '重点学校'=>[
            'cost'=>16000,
            'days'=>30,
            'lore'=>5
        ],
        '名牌大学'=>[
            'cost'=>30000,
            'days'=>30,
            'lore'=>10
        ],
    ],
    'Blessing'=>[
        'cost'=>8000,
        'days'=>0,
        'lucky'=>[
            1=>[
                'value'=>0.5,
                'lucky'=>1,
            ],
            2=>[
                'value'=>0.45,
                'lucky'=>0,
            ],
            3=>[
                'value'=>0.05,
                'lucky'=>2,
            ],
        ]
    ],
    'Fitness'=>[
        'cost'=>300,
        'mood'=>1,
        'power'=>10,
        'days'=>0,
    ],
];
